"""Generate ``docs/model_card.md`` and ``docs/data_card.md`` from the committed reports.

Every number in the cards is read from a report JSON written by code, so the cards
cannot drift from the results.
"""

from __future__ import annotations

import json
from pathlib import Path

from fraud.config import REPO_ROOT, reports_dir


def _load(name: str) -> dict:
    return json.loads((reports_dir() / name).read_text())


def _usd(v: float) -> str:
    return f"${v:,.0f}"


def model_card() -> str:
    m = _load("model_metrics.json")
    p = _load("policy_results.json")
    e = _load("explainability.json")
    frozen = p["frozen"]
    lg = m["lightgbm"]["test"]
    rules = p["test"]["rules"]
    chosen = p["test"][p["chosen"]]
    rec = {r["fpr_target"]: r for r in lg["recall_at_fpr"]}
    seg = e["segments"]
    masked_top = sum(v for k, v in e["top_reason_family_share"].items() if "(masked)" in k)
    lat = m["diagnostic"]["single_event_ms"]
    expl_extra = (
        e["comparison"]["explainable"]["test"]["total_cost"]
        - e["comparison"]["all"]["test"]["total_cost"]
    )

    def seg_range(segment: str, key: str) -> str:
        vals = [
            s[key]
            for s in seg
            if s["segment"] == segment and s[key] is not None and s["transactions"] >= 1000
        ]
        return f"{min(vals):.1%} to {max(vals):.1%}" if vals else "—"

    lines = [
        "# Model card: card fraud scoring (LightGBM, all features)",
        "",
        "Generated by `fraud cards` from `reports/*.json`. Amounts are USD.",
        "",
        "## Model",
        "",
        "- **What it is:** a LightGBM binary classifier giving a calibrated probability that a",
        "  card-not-present transaction is fraud, used by an expected-loss decision policy",
        "  that approves, declines or sends the transaction to a manual review queue.",
        f"- **Inputs:** {e['comparison']['all']['features']} features: 17 point-in-time history",
        "  aggregates (docs/features.md), 19 readable transaction fields and Vesta's masked",
        "  columns (C, D, M, V, identity).",
        "- **Training:** December 2017 to March 2018; tuned on April 2018; tested on May 2018.",
        f"  Calibration: {m['lightgbm'].get('calibration', 'see reports/model.md')}, chosen on",
        "  a time split inside April.",
        f"- **Decision policy (frozen on validation):** `{frozen['policy']['type']}`, review when",
        f"  the expected saving exceeds ${frozen['policy']['review_threshold']:,.2f}, at most",
        f"  {frozen['costs']['review_capacity_per_day']} reviews a day; costs in "
        "configs/costs.yaml.",
        "",
        "## Intended use",
        "",
        "- Ranking and routing e-commerce card transactions for decline or analyst review, with",
        "  an analyst in the loop for reviews and a route for declined customers to appeal.",
        "- Not for: credit or affordability decisions, assessing individuals outside a",
        "  transaction, merchants or products unlike the training data, or automatic declines",
        "  without a way for a customer to get the decision reviewed.",
        "",
        "## Performance (test month, May 2018)",
        "",
        f"- PR-AUC {lg['pr_auc']:.3f} (fraud rate {lg['fraud'] / lg['rows']:.2%}); ROC-AUC "
        f"{lg['roc_auc']:.3f}.",
        f"- Recall at a 1% false-positive rate: {rec[0.01]['recall']:.1%} of fraud "
        f"transactions, {rec[0.01]['value_recall']:.1%} of fraud dollars.",
        f"- Calibration: Brier {lg['brier']:.4f}, expected calibration error {lg['ece']:.4f}.",
        f"- **In money:** the frozen policy cost {_usd(chosen['total_cost'])} and caught "
        f"{chosen['fraud_value_caught_share']:.1%} of fraud value; the rules baseline cost "
        f"{_usd(rules['total_cost'])} ({rules['fraud_value_caught_share']:.1%} caught).",
        (
            "- The policy costs less than the rules baseline at both ends of every cost "
            "assumption's range (reports/policy.md)."
            if all(r["policy_test_cost"] < r["rules_test_cost"] for r in p["sensitivity"])
            else "- The saving does **not** hold at every end of the cost ranges; see "
            "reports/policy.md."
        ),
        "",
        "## Explainability",
        "",
        "Each decision carries its top three SHAP reasons in plain names. Masked columns can",
        "only be named by family; "
        f"{masked_top:.0%} of alerts have a masked column as their top reason. Scoring one "
        f"transaction with its reasons takes {lat['score_and_reasons_p50']:.1f} ms (p99 "
        f"{lat['score_and_reasons_p99']:.1f} ms), which is why trees are capped at depth 8. "
        "A model on explainable features only costs "
        f"{_usd(expl_extra)} "
        "more on the test month (reports/explainability.md).",
        "",
        "## Segments (not a fairness audit)",
        "",
        "The data has no protected characteristics, so fairness cannot be assessed. Across",
        "segments with at least 1,000 test transactions, the alert rate ranges "
        f"{seg_range('ProductCD', 'alert_rate')} by product and "
        f"{seg_range('card6', 'alert_rate')} by card type; recall ranges "
        f"{seg_range('ProductCD', 'recall')} by product. Details in reports/explainability.md.",
        "",
        "## Monitoring and retraining",
        "",
        "Drift on inputs and scores daily over 7 days; performance per weekly cohort once its",
        "labels arrive (30 days); thresholds and the retrain rule in configs/monitoring.yaml and",
        "reports/monitoring.md.",
        "",
        "## Limitations and risks",
        "",
        "- The pseudo-card key merges and splits real cards (reports/data.md); 11% of rows have",
        "  a coarse key.",
        "- Vesta's masked columns cannot be checked for availability at transaction time.",
        "- The data is from 2017-18 and from one provider; fraud patterns move.",
        "- The cost model is a set of assumptions; the sensitivity table shows the ranking of",
        "  policies holds across them, not that the dollar figures are exact.",
        "- The time anchor (2017-11-30) is inferred, not published.",
        "- The validation month's labels would not all be known on the day the policy was",
        "  frozen (30-day delay); the offline split ignores that, the monitoring does not.",
        "",
        "## Governance",
        "",
        "Every decision is in DECISIONS.md; every read of the test month is logged in",
        "reports/test_touches.jsonl. A production deployment would add an independent",
        "model-risk review, challenger models, and case-management feedback into labels.",
        "",
    ]
    return "\n".join(lines)


def data_card() -> str:
    d = _load("data_profile.json")
    splits = {s["split"]: s for s in d["splits"]}
    ck = d["card_key"]
    total = sum(s["transactions"] for s in splits.values())
    fraud = sum(s["fraud"] for s in splits.values())
    lines = [
        "# Data card: IEEE-CIS Fraud Detection (Vesta)",
        "",
        "Generated by `fraud cards` from `reports/data_profile.json`.",
        "",
        "## Source and licence",
        "",
        "- Kaggle competition *IEEE-CIS Fraud Detection* (2019), data from Vesta Corporation,",
        "  real e-commerce card-not-present transactions.",
        "- Rules (section 7): non-commercial use only, including education and research; no",
        "  redistribution. This repository therefore holds no raw rows; CI uses synthetic data.",
        "- Only the two training files are used (`train_transaction.csv`,",
        "  `train_identity.csv`); Kaggle's test files have no labels.",
        "",
        "## Contents",
        "",
        f"- {total:,} transactions, {fraud:,} fraud ({fraud / total:.2%}), about six months;",
        "  amounts in US dollars.",
        "- 394 transaction columns and 41 identity columns (24% of transactions have an",
        "  identity record). Most are masked by Vesta: C (counts), D (time deltas), M (matches),",
        "  V (Vesta's engineered signals), id_01-id_38.",
        "- Time is seconds from an undisclosed point; this project anchors it at 2017-11-30",
        "  (DECISIONS.md), which puts the data in December 2017 to May 2018.",
        "",
        "| Split | Period | Transactions | Fraud rate |",
        "|---|---|---|---|",
        *(
            f"| {k} | {s['first_day']} to {s['last_day']} | {s['transactions']:,} "
            f"| {s['fraud_rate']:.2%} |"
            for k, s in splits.items()
        ),
        "",
        "## Labels",
        "",
        "`isFraud` comes from reported chargebacks. According to Vesta's description on the",
        "competition forum, transactions linked to a charged-back card by account, email or",
        "billing address after the chargeback are labelled fraud too, and a transaction counts",
        "as legitimate when nothing is reported within about 120 days. Labels are therefore",
        "partly card-level and arrive late; this project releases each label 30 days after",
        "its transaction in the stream simulation.",
        "",
        "## Identifiers and personal data",
        "",
        "No names, card numbers or addresses; card and address fields are masked codes. There",
        "is no card ID: the pseudo-card key (card1 + addr1 + first-seen day) gives "
        f"{ck['keys']:,} keys, {ck['share_rows_in_repeat_keys']:.1%} of rows with history, "
        f"{ck['repeat_keys_card_fields_constant']:.1%} of repeat keys consistent with one card.",
        "There are **no protected characteristics** (age, sex, ethnicity and so on).",
        "",
        "## Quality",
        "",
        "Silver's checks (keys, types, allowed values, ranges, identity orphans) pass with zero",
        "failing rows; no duplicates. Missingness is heavy and structured: most V and identity",
        "columns are empty for most rows.",
        "",
    ]
    return "\n".join(lines)


def write_cards(docs: Path = REPO_ROOT / "docs") -> list[Path]:
    out = []
    for name, text in (("model_card.md", model_card()), ("data_card.md", data_card())):
        path = docs / name
        path.write_text(text)
        out.append(path)
    return out
