"""Write ``reports/explainability.md`` from the phase 6 results."""

from __future__ import annotations

from pathlib import Path

from fraud.model.data import list_test_touches

SEGMENT_NAMES = {
    "ProductCD": "Product code",
    "card4": "Card network",
    "card6": "Card type",
    "DeviceType": "Device type",
    "P_emaildomain": "Purchaser email domain",
}


def _usd(v: float) -> str:
    return f"${v:,.0f}"


def _pct(v) -> str:
    return "—" if v is None else f"{v:.1%}"


def write_explain_report(r: dict, out_dir: Path) -> None:
    c = r["comparison"]
    a, e = c["all"]["test"], c["explainable"]["test"]
    diff = e["total_cost"] - a["total_cost"]
    lines = [
        "# Explainability and governance",
        "",
        "Generated by `fraud explain`. Amounts are USD. The explainable model was tuned and its",
        "policy threshold chosen on the validation month; the test month was read once for",
        f"this report ({len(list_test_touches())} test reads in total so far, logged in",
        "`reports/test_touches.jsonl`).",
        "",
        "## What the masked features are worth in money",
        "",
        "The same LightGBM set-up (grid, early stopping, calibration, expected-loss policy",
        "tuned on validation) with two feature sets:",
        "",
        "| Feature set | Features | Test PR-AUC | Test total cost | Fraud value caught | Valid "
        "PR-AUC | Valid total cost |",
        "|---|---|---|---|---|---|---|",
    ]
    for name, label in (
        ("all", "All (incl. Vesta's masked columns)"),
        ("explainable", "Explainable only"),
    ):
        m = c[name]
        lines.append(
            f"| {label} | {m['features']} | {m['test']['pr_auc']:.3f} "
            f"| {_usd(m['test']['total_cost'])} | {m['test']['fraud_value_caught_share']:.1%} "
            f"| {m['valid']['pr_auc']:.3f} | {_usd(m['valid']['total_cost'])} |"
        )
    lines += [
        "",
        f"Leaving out the masked columns costs **{_usd(diff)} more on the test month** "
        f"({diff / a['total_cost']:.0%} of the all-features cost) and catches "
        f"{(a['fraud_value_caught_share'] - e['fraud_value_caught_share']) * 100:.1f} "
        "percentage points less fraud value. That is the price of a model whose every input "
        "a reviewer can be told about; whether it is worth paying is a business and model-risk "
        "decision, and this number is what that decision needs.",
        "",
        "## Reason codes",
        "",
        "Every decision carries its top three reasons: the features with the largest positive",
        "SHAP contributions (LightGBM's TreeSHAP, `pred_contrib`), each with a plain name and",
        "the transaction's value. Masked columns can only be named by the family Vesta",
        'published (for example "V258 — Vesta risk signal (masked)"), which is the governance',
        "problem the table above prices.",
        "",
        f"Across the {r['alerts']:,} test transactions the frozen policy declined or sent to",
        "review, the top reason came from:",
        "",
        "| Family of the top reason | Share of alerts |",
        "|---|---|",
        *(f"| {k} | {v:.1%} |" for k, v in r["top_reason_family_share"].items()),
        "",
        "The most frequent single top reasons:",
        "",
        "| Feature | Share of alerts |",
        "|---|---|",
        *(
            f"| {x['name']} (`{x['feature']}`) | {x['share']:.1%} |"
            for x in r["top_reason_feature_share"]
        ),
        "",
        "## Global importance (mean |SHAP|, validation month)",
        "",
        "Share of total mean |SHAP| by feature family, all-features model:",
        "",
        "| Family | Share |",
        "|---|---|",
        *(f"| {k} | {v:.1%} |" for k, v in r["shap_share_by_family"].items()),
        "",
        "Top 20 features, all-features model:",
        "",
        "| Feature | Plain name | Mean abs SHAP (log-odds) |",
        "|---|---|---|",
        *(
            f"| `{x['feature']}` | {x['name']} | {x['mean_abs_shap']:.3f} |"
            for x in r["shap_all_top20"]
        ),
        "",
        "Top 20 features, explainable model:",
        "",
        "| Feature | Plain name | Mean abs SHAP (log-odds) |",
        "|---|---|---|",
        *(
            f"| `{x['feature']}` | {x['name']} | {x['mean_abs_shap']:.3f} |"
            for x in r["shap_explainable_top20"]
        ),
        "",
        "## Segment checks (test month, frozen policy)",
        "",
        "An alert is a decline or a review. Precision is the share of alerts that were fraud;",
        "recall is the share of fraud transactions alerted; value caught is the share of fraud",
        "dollars stopped (declines, plus reviews times the analyst catch rate).",
        "",
        "**This is not a fairness audit.** The data has no protected characteristics (age, sex,",
        "ethnicity, disability and so on), and the segments below are commercial attributes. A",
        "fairness audit would need those characteristics (or a defensible proxy, collected",
        "lawfully), a stated fairness criterion (for example equal false-decline rates across",
        "groups), and outcome data on the customers declined. What these checks can show is",
        "whether the policy's burden falls very unevenly across products, card types and",
        "channels, which a model-risk review would ask about anyway.",
        "",
    ]
    for seg in SEGMENT_NAMES:
        rows = [x for x in r["segments"] if x["segment"] == seg]
        rows.sort(key=lambda x: -x["transactions"])
        lines += [
            f"**{SEGMENT_NAMES[seg]}**",
            "",
            "| Value | Transactions | Fraud rate | Alert rate | Precision | Recall "
            "| Value caught |",
            "|---|---|---|---|---|---|---|",
            *(
                f"| {x['value']} | {x['transactions']:,} | {_pct(x['fraud_rate'])} "
                f"| {_pct(x['alert_rate'])} | {_pct(x['precision'])} | {_pct(x['recall'])} "
                f"| {_pct(x['value_caught'])} |"
                for x in rows
            ),
            "",
        ]
    (out_dir / "explainability.md").write_text("\n".join(lines))
