"""Write ``reports/stream.md`` from a stream run."""

from __future__ import annotations

from pathlib import Path


def _ms(d: dict) -> str:
    return " / ".join(f"{d[k]:.2f}" for k in ("p50", "p95", "p99")) + f" (max {d['max']:.1f})"


def _speed(r: dict) -> str:
    return "as fast as possible" if not r["speedup"] else f"{r['speedup']:g}× real time"


def _latency_row(x: dict) -> str:
    p = x["processor"]
    e2e = _ms(p["end_to_end_ms"]) if p.get("end_to_end_ms") else "—"
    return (
        f"| {_speed(x)} | {p['events']:,} | {p['events_per_second']:,.0f} "
        f"| {_ms(p['processing_ms'])} | {e2e} |"
    )


def write_stream_report(runs: list[dict], out_dir: Path) -> None:
    """One report from the replays run so far (typically as fast as possible, and paced)."""
    runs = sorted(runs, key=lambda r: r["speedup"])
    r = runs[0]
    p = r["processor"]
    par = r["parity"]
    produced = r["produced"]
    speed = _speed(r)
    agree = par["actions_agree"] / par["actions_compared"]
    lines = [
        "# Streaming",
        "",
        "Generated by `fraud stream`. The test month was replayed through Redpanda: a",
        "producer published each transaction at its event time and each label 30 days later,",
        "a stream processor computed online features, scored, explained and decided every",
        "transaction, and Spark Structured Streaming landed all three topics in Delta bronze.",
        "",
        f"- Window: {r['window'][0]} to {r['window'][1]}, replayed {speed}.",
        f"- Published: {produced['transactions']:,} transactions and {produced['labels']:,} "
        "labels: April's labels as they fall due in May, then, with the clock running on "
        f"for {r['label_tail_days']} days after the last transaction, May's own labels.",
        f"- Processor state warmed with {p['warm_transactions']:,} earlier transactions from the "
        "lake; at the end it held "
        + ", ".join(f"{v:,} {k.replace('_key', '')} keys" for k, v in p["keys_in_state"].items())
        + ".",
        "- Bronze rows landed: "
        + ", ".join(f"{k} {v:,}" for k, v in r["bronze_rows"].items())
        + f" (sink run {r['sink_seconds']} s).",
        "",
        "## Parity: stream against offline",
        "",
        "Every feature the processor published, read back from the Delta bronze table,",
        "compared with the offline Spark feature table for the same transaction:",
        "",
        "| Check | Result |",
        "|---|---|",
        f"| Transactions compared | {par['rows_compared']:,} of {par['window_rows']:,} in the "
        "window |",
        f"| Values compared | {par['rows_compared'] * par['features_compared']:,} "
        f"({par['features_compared']} per transaction: 17 aggregates and 3 entity keys) |",
        f"| Feature mismatches | **{par['feature_mismatches']:,}** |",
        f"| Actions equal to the frozen policy applied offline | {par['actions_agree']:,} of "
        f"{par['actions_compared']:,} ({agree:.2%}) |",
        f"| Largest difference in P(fraud), online vs offline | "
        f"{par['max_abs_score_difference']:.2e} |",
        f"| Decisions published without a reason | {par['decisions_without_reasons']:,} |",
        "",
        "Actions taken: " + ", ".join(f"{k} {v:,}" for k, v in par["actions"].items()) + ".",
        "",
        "## Latency and throughput",
        "",
        "Measured on one laptop process (Apple silicon), one partition, one event at a time.",
        "Processing is the processor's own time per event: online features, the LightGBM",
        "score with TreeSHAP reasons, and the policy. End to end runs from the producer",
        "sending the transaction to the processor publishing its decision, so it includes",
        "Kafka and any time the event waited in the topic.",
        "",
        "| Replay | Events | Decisions per second | Processing p50 / p95 / p99 (ms) "
        "| End to end p50 / p95 / p99 (ms) |",
        "|---|---|---|---|---|",
        *(_latency_row(x) for x in runs),
        "",
        "Replayed as fast as possible, the decisions per second are the processor's capacity,",
        "and end-to-end latency is mostly queueing behind the backlog the producer builds.",
        "At a paced speed the processor keeps up, so end-to-end latency is what a transaction",
        "would see. The test month averages about 2,900 transactions a day.",
        "",
    ]
    (out_dir / "stream.md").write_text("\n".join(lines))
