"""Write ``reports/policy.md`` from the policy results."""

from __future__ import annotations

from pathlib import Path

from fraud.model.data import list_test_touches
from fraud.policy.costs import CostModel

LABELS = {
    "approve_all": "Approve everything (no screening)",
    "rules": "Rules baseline (points, decline and review levels)",
    "logreg_expected_loss": "Logistic regression, expected-loss policy",
    "lightgbm_cutoffs": "LightGBM, probability cut-offs",
    "lightgbm_expected_loss": "LightGBM, expected-loss policy",
}
PARAM_LABELS = {
    "chargeback_fee": "Chargeback fee ($)",
    "review_cost": "Review cost ($)",
    "review_catch_rate": "Analyst catch rate",
    "decline_margin": "Lost margin on a false decline (share of amount)",
    "decline_fixed": "Fixed cost of a false decline ($)",
    "review_delay_friction": "Delay cost of a reviewed good order ($)",
    "review_capacity_per_day": "Review capacity per day",
}


def _usd(v: float) -> str:
    return f"${v:,.0f}"


def _policy_table(results: dict) -> list[str]:
    lines = [
        "| Policy | Total cost | Fraud value caught | Missed fraud | False-decline friction "
        "| Reviews (cost incl. delay) | Declines (of which legitimate) "
        "| Reviews (of which fraud) |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for name, r in results.items():
        lines.append(
            f"| {LABELS[name]} | **{_usd(r['total_cost'])}** | "
            f"{r['fraud_value_caught_share']:.1%} of {_usd(r['fraud_value'])} "
            f"| {_usd(r['missed_fraud_cost'])} | {_usd(r['declined_legit_cost'])} "
            f"| {_usd(r['review_cost'] + r['review_delay_cost'])} "
            f"| {r['declines']:,} ({r['declined_legit']:,}) | {r['reviews']:,} "
            f"({r['reviewed_fraud']:,}) |"
        )
    return lines


def write_policy_report(result: dict, costs: CostModel, out_dir: Path) -> None:
    chosen = result["chosen"]
    t = result["test"]
    rules = t["rules"]
    pick = t[chosen]
    saving = rules["total_cost"] - pick["total_cost"]
    headline = (
        f"On the most recent month (May 2018, the test month), the chosen review policy "
        f"({LABELS[chosen]}) catches **{pick['fraud_value_caught_share']:.1%} of fraud value** "
        f"at a cost of **{_usd(pick['total_cost'])}**, against **{_usd(rules['total_cost'])}** "
        f"for the rules baseline, which catches {rules['fraud_value_caught_share']:.1%}. "
        f"That is {_usd(saving)} less ({saving / rules['total_cost']:.0%}). Approving "
        f"everything would have cost {_usd(t['approve_all']['total_cost'])}."
    )
    lines = [
        "# Decision policy and money",
        "",
        "Generated by `fraud policy`. Amounts are USD. Policies were tuned and the policy was",
        "chosen on the validation month (April 2018); the choice was written to",
        "`reports/policy_frozen.json` before the test month was read, and the test month was",
        "then read once for this whole report (logged in `reports/test_touches.jsonl`,",
        f"{len(list_test_touches())} reads in total so far).",
        "",
        "## Headline",
        "",
        headline,
        "",
        "## Test month (May 2018)",
        "",
        *_policy_table(t),
        "",
        "## Validation month (April 2018), where the policies were tuned and chosen",
        "",
        *_policy_table(result["valid"]),
        "",
        "Tuned settings:",
        "",
        *(f"- **{LABELS[n]}**: {text}." for n, text in result["settings"].items()),
        "",
        "## The cost model",
        "",
        "From `configs/costs.yaml`; each value has its rationale there and in DECISIONS.md.",
        "",
        "- **Approve**: a fraud costs the amount plus the chargeback fee.",
        "- **Decline**: a legitimate customer costs the lost margin (a share of the amount) "
        "plus a fixed amount.",
        "- **Review**: costs the analyst's time; the analyst stops a share of the fraud; a "
        "legitimate order is approved late at a small cost.",
        f"- **Capacity**: at most {costs.review_capacity_per_day} reviews a day, allocated "
        "in arrival order: the queue cannot see the rest of the day, so a policy that wastes "
        "early slots on low-value cases has none left for large ones.",
        "",
        "| Assumption | Default | Sensitivity range |",
        "|---|---|---|",
    ]
    for p, (lo, hi) in CostModel.ranges().items():
        lines.append(f"| {PARAM_LABELS[p]} | {getattr(costs, p):g} | {lo:g} to {hi:g} |")
    lines += [
        "",
        "## Ranking for review: expected saving against probability (validation)",
        "",
        "Both rankings get the same number of reviews: the top "
        f"{costs.review_capacity_per_day} of each day with hindsight over the day (so the "
        "comparison is about the ranking alone, not the queueing), everything else approved,",
        "no declines. LightGBM's calibrated probabilities.",
        "",
        "| Review the daily top by | Total cost | Fraud value caught | Reviews that were fraud |",
        "|---|---|---|---|",
    ]
    for label, r in result["rankings_valid"].items():
        lines.append(
            f"| {label} | {_usd(r['total_cost'])} | {r['fraud_value_caught_share']:.1%} "
            f"| {r['reviewed_fraud']:,} of {r['reviews']:,} |"
        )
    saving, prob = (
        result["rankings_valid"]["expected saving"],
        result["rankings_valid"]["probability"],
    )
    diff = prob["total_cost"] - saving["total_cost"]
    lines += [
        "",
        "The expected saving is P × (amount + fee) × catch rate − review cost − (1 − P) × delay "
        "cost: the brief's P(fraud) × amount − review cost, plus the fee, the analyst's misses "
        "and the delay. ",
        (
            f"Ranking by it costs {_usd(diff)} less over the month than ranking by probability. "
            "It sends fewer actual frauds to review but larger ones: a 60% chance on a $2,000 "
            "order is worth reviewing before a 90% chance on a $20 one."
            if diff > 0
            else f"Ranking by it costs {_usd(-diff)} **more** than ranking by probability, "
            "so here the probability ranking wins."
        ),
        "",
        "## Sensitivity (test month)",
        "",
        "Each row changes one assumption to the end of its range, re-tunes the rules and the "
        "chosen policy type on validation under that assumption, and costs both on test.",
        "",
        "| Assumption | Value | Rules baseline | Chosen policy | Saving | Fraud value caught "
        "(policy) | Approve everything |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in result["sensitivity"]:
        sv = r["rules_test_cost"] - r["policy_test_cost"]
        lines.append(
            f"| {PARAM_LABELS[r['parameter']]} | {r['value']:g} | {_usd(r['rules_test_cost'])} "
            f"| {_usd(r['policy_test_cost'])} | {_usd(sv)} ({sv / r['rules_test_cost']:.0%}) "
            f"| {r['policy_test_caught_share']:.1%} | {_usd(r['approve_all_test_cost'])} |"
        )
    worst = min(result["sensitivity"], key=lambda r: r["rules_test_cost"] - r["policy_test_cost"])
    lines += [
        "",
        f"The smallest saving in the table is "
        f"{_usd(worst['rules_test_cost'] - worst['policy_test_cost'])}, with "
        f"{PARAM_LABELS[worst['parameter']].lower()} at {worst['value']:g}.",
        "",
    ]
    (out_dir / "policy.md").write_text("\n".join(lines))
