"""Profile the gold table: volumes, the time anchor check, and card-key stability.

Everything written here is an aggregate. ``reports/data.md`` is generated by this
module and committed; no row-level value is ever written out.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

from pyspark.sql import DataFrame, SparkSession
from pyspark.sql import functions as F

from fraud.config import Settings
from fraud.lakehouse.tables import GOLD_TRANSACTIONS, table_path
from fraud.spark import on_databricks

log = logging.getLogger(__name__)


def split_summary(gold: DataFrame) -> list[dict]:
    rows = (
        gold.groupBy("split")
        .agg(
            F.min("event_date").alias("first_day"),
            F.max("event_date").alias("last_day"),
            F.count(F.lit(1)).alias("transactions"),
            F.sum("isFraud").alias("fraud"),
            F.avg("isFraud").alias("fraud_rate"),
            F.sum("TransactionAmt").alias("amount_usd"),
            F.sum(F.when(F.col("isFraud") == 1, F.col("TransactionAmt"))).alias("fraud_usd"),
            F.avg(F.col("has_identity").cast("double")).alias("identity_share"),
        )
        .collect()
    )
    order = {"train": 0, "valid": 1, "test": 2}
    return sorted((r.asDict() for r in rows), key=lambda r: order.get(r["split"], 9))


def monthly(gold: DataFrame) -> list[dict]:
    return [
        r.asDict()
        for r in gold.groupBy("event_month")
        .agg(
            F.count(F.lit(1)).alias("transactions"),
            F.avg("isFraud").alias("fraud_rate"),
            F.sum(F.when(F.col("isFraud") == 1, F.col("TransactionAmt"))).alias("fraud_usd"),
        )
        .orderBy("event_month")
        .collect()
    ]


def daily(gold: DataFrame):
    return gold.groupBy("event_date").count().orderBy("event_date").toPandas()


def card_key_stability(gold: DataFrame) -> dict:
    """How well the pseudo-card key behaves like a card.

    A real card has one network, type and issuer BIN, so a key that mixes several is
    merging cards. If D1 rounding split cards, pairs of keys with the same card1 and
    addr1 whose first-seen days are one apart would be over-represented compared with
    pairs two to five days apart (which arise only from different cards sharing card1 and
    addr1). The excess estimates how many cards the rounding splits.
    """
    parts = F.split("card_key", "_")
    g = gold.withColumn("_na", (parts[1] == "NA") | (parts[2] == "NA"))
    total = g.count()
    per_key = g.groupBy("card_key").agg(
        F.count(F.lit(1)).alias("n"),
        F.countDistinct("card4").alias("n_card4"),
        F.countDistinct("card6").alias("n_card6"),
        F.countDistinct("card2").alias("n_card2"),
        F.countDistinct("card5").alias("n_card5"),
        F.countDistinct("P_emaildomain").alias("n_email"),
        F.max("isFraud").alias("any_fraud"),
        F.min("isFraud").alias("all_fraud"),
        F.first("_na").alias("na"),
    )
    multi = per_key.filter(F.col("n") >= 2)
    q = per_key.approxQuantile("n", [0.5, 0.9, 0.99], 0.001)
    agg = per_key.agg(
        F.count(F.lit(1)).alias("keys"),
        F.max("n").alias("max_n"),
        F.sum(F.when(F.col("n") >= 2, F.col("n")).otherwise(0)).alias("rows_in_repeat_keys"),
        F.sum(F.when(F.col("na"), F.col("n")).otherwise(0)).alias("rows_with_na_part"),
    ).collect()[0]
    m = multi.agg(
        F.count(F.lit(1)).alias("multi_keys"),
        F.avg(
            (
                (F.col("n_card4") <= 1)
                & (F.col("n_card6") <= 1)
                & (F.col("n_card2") <= 1)
                & (F.col("n_card5") <= 1)
            ).cast("double")
        ).alias("card_fields_constant"),
        F.avg((F.col("n_email") <= 1).cast("double")).alias("email_constant"),
        F.avg(((F.col("any_fraud") == 1) & (F.col("all_fraud") == 0)).cast("double")).alias(
            "mixed_labels"
        ),
    ).collect()[0]

    keys = (
        per_key.withColumn("_p", F.split("card_key", "_"))
        .filter(F.col("_p")[2] != "NA")
        .select(
            F.concat_ws("_", F.col("_p")[0], F.col("_p")[1]).alias("ca"),
            F.col("_p")[2].cast("long").alias("first_seen"),
        )
    )
    if not on_databricks():
        keys = keys.cache()
    gaps = {}
    for gap in range(1, 6):
        shifted = keys.select("ca", (F.col("first_seen") - F.lit(gap)).alias("first_seen"))
        gaps[gap] = keys.join(shifted, ["ca", "first_seen"]).count()
    if not on_databricks():
        keys.unpersist()
    baseline = sum(gaps[g] for g in range(2, 6)) / 4
    return {
        "rows": total,
        "keys": int(agg["keys"]),
        "rows_per_key_median": q[0],
        "rows_per_key_p90": q[1],
        "rows_per_key_p99": q[2],
        "rows_per_key_max": int(agg["max_n"]),
        "share_rows_in_repeat_keys": agg["rows_in_repeat_keys"] / total,
        "share_rows_with_missing_addr1_or_d1": agg["rows_with_na_part"] / total,
        "repeat_keys": int(m["multi_keys"]),
        "repeat_keys_card_fields_constant": m["card_fields_constant"],
        "repeat_keys_email_constant": m["email_constant"],
        "repeat_keys_mixed_labels": m["mixed_labels"],
        "key_pairs_by_first_seen_gap": gaps,
        "one_day_pairs_excess_over_2_5_day_mean": gaps[1] - baseline,
    }


def _fmt_usd(v: float | None) -> str:
    return "—" if v is None else f"${v:,.0f}"


def write_report(spark: SparkSession, s: Settings, out_dir: Path) -> dict:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    gold = spark.read.format("delta").load(table_path(s, GOLD_TRANSACTIONS))
    if not on_databricks():  # serverless compute does not cache DataFrames
        gold = gold.cache()
    splits = split_summary(gold)
    months = monthly(gold)
    days = daily(gold)
    stability = card_key_stability(gold)
    top_days = days.sort_values("count", ascending=False).head(5)
    weekday = (
        gold.groupBy(F.date_format("event_ts", "E").alias("weekday"))
        .count()
        .orderBy(F.desc("count"))
        .toPandas()
    )
    if not on_databricks():
        gold.unpersist()

    out_dir.mkdir(parents=True, exist_ok=True)
    fig_dir = out_dir / "figures"
    fig_dir.mkdir(exist_ok=True)
    fig, ax = plt.subplots(figsize=(9, 3))
    ax.plot(days["event_date"], days["count"], lw=1)
    for name, iv in (("valid", s.split.valid), ("test", s.split.test)):
        ax.axvline(iv.start, color="grey", ls="--", lw=0.8)
        ax.text(iv.start, ax.get_ylim()[1] * 0.95, f" {name}", fontsize=8, va="top")
    ax.set_ylabel("transactions per day")
    ax.set_title(f"Daily volume (anchor {s.anchor.date()})", fontsize=10)
    fig.tight_layout()
    fig.savefig(fig_dir / "daily_volume.png", dpi=120)
    plt.close(fig)

    lines = [
        "# Data profile",
        "",
        "Generated by `fraud profile` from the gold table. Aggregates only. Amounts are USD.",
        "",
        "## Splits",
        "",
        "| Split | First day | Last day | Transactions | Fraud | Fraud rate | Amount "
        "| Fraud amount | With identity |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for r in splits:
        lines.append(
            f"| {r['split']} | {r['first_day']} | {r['last_day']} | {r['transactions']:,} "
            f"| {r['fraud']:,} | {r['fraud_rate']:.2%} | {_fmt_usd(r['amount_usd'])} "
            f"| {_fmt_usd(r['fraud_usd'])} | {r['identity_share']:.1%} |"
        )
    lines += ["", "## By month", "", "| Month | Transactions | Fraud rate | Fraud amount |"]
    lines.append("|---|---|---|---|")
    for r in months:
        lines.append(
            f"| {r['event_month']} | {r['transactions']:,} | {r['fraud_rate']:.2%} "
            f"| {_fmt_usd(r['fraud_usd'])} |"
        )
    lines += [
        "",
        "## Time anchor check",
        "",
        f"With `TransactionDT = 0` at {s.anchor.isoformat()} UTC, the busiest days are:",
        "",
        "| Day | Transactions |",
        "|---|---|",
        *(f"| {r.event_date} | {r['count']:,} |" for _, r in top_days.iterrows()),
        "",
        "Transactions by weekday under this anchor: "
        + ", ".join(f"{r.weekday} {r['count']:,}" for _, r in weekday.iterrows())
        + ".",
        "",
        "![daily volume](figures/daily_volume.png)",
        "",
        "## Pseudo-card key stability",
        "",
        "`card_key = card1 _ addr1 _ (transaction day − D1)`; see `fraud/features/keys.py`.",
        "",
        "| Measure | Value |",
        "|---|---|",
        f"| Rows | {stability['rows']:,} |",
        f"| Distinct keys | {stability['keys']:,} |",
        f"| Rows per key: median / p90 / p99 / max | {stability['rows_per_key_median']:.0f} / "
        f"{stability['rows_per_key_p90']:.0f} / {stability['rows_per_key_p99']:.0f} / "
        f"{stability['rows_per_key_max']:,} |",
        f"| Rows whose key has history (≥2 rows) | {stability['share_rows_in_repeat_keys']:.1%} |",
        f"| Rows with addr1 or D1 missing (weaker key) | "
        f"{stability['share_rows_with_missing_addr1_or_d1']:.1%} |",
        f"| Repeat keys with one card4/card6/card2/card5 (consistent with one card) | "
        f"{stability['repeat_keys_card_fields_constant']:.1%} |",
        f"| Repeat keys with one email domain | {stability['repeat_keys_email_constant']:.1%} |",
        f"| Repeat keys with both fraud and non-fraud rows | "
        f"{stability['repeat_keys_mixed_labels']:.1%} |",
        "| Key pairs sharing card1+addr1 with first-seen days 1 / 2 / 3 / 4 / 5 apart | "
        + " / ".join(f"{stability['key_pairs_by_first_seen_gap'][g]:,}" for g in range(1, 6))
        + " |",
        f"| Excess of 1-day pairs over the 2-5 day mean (cards likely split by D1 rounding) | "
        f"{stability['one_day_pairs_excess_over_2_5_day_mean']:,.0f} |",
        "",
    ]
    (out_dir / "data.md").write_text("\n".join(lines))
    metrics = {"splits": splits, "months": months, "card_key": stability}
    (out_dir / "data_profile.json").write_text(json.dumps(metrics, indent=2, default=str) + "\n")
    log.info("wrote %s", out_dir / "data.md")
    return metrics
