"""Write ``reports/model_comparison.md`` from the rolling-origin comparison."""

from __future__ import annotations

from pathlib import Path

NAMES = {"lightgbm": "LightGBM", "xgboost": "XGBoost", "catboost": "CatBoost"}
MONTHS = {"2018-02": "February", "2018-03": "March", "2018-04": "April"}


def _usd(v: float) -> str:
    return f"-${-v:,.0f}" if v < 0 else f"${v:,.0f}"


def _signed(v: float) -> str:
    return f"+{_usd(v)}" if v > 0 else _usd(v)


def verdict(result: dict) -> list[str]:
    summary = result["summary"]
    base = summary["lightgbm"]
    lines = []
    for lib, s in summary.items():
        if lib == "lightgbm":
            continue
        d = s["cost_vs_lightgbm"]
        pct = [x / c for x, c in zip(d, base["total_cost"], strict=True)]
        name = NAMES[lib]
        if all(x < 0 for x in d):
            lines.append(
                f"{name} is cheaper than LightGBM in all {len(d)} months, by "
                f"{_usd(-max(d))} to {_usd(-min(d))} ({-max(pct):.1%} to {-min(pct):.1%})."
            )
        elif all(x > 0 for x in d):
            lines.append(
                f"{name} costs more than LightGBM in all {len(d)} months, by "
                f"{_usd(min(d))} to {_usd(max(d))} ({min(pct):.1%} to {max(pct):.1%})."
            )
        else:
            cheaper = sum(x < 0 for x in d)
            lines.append(
                f"{name} is cheaper than LightGBM in {cheaper} of {len(d)} months; the "
                f"difference changes sign ({', '.join(_signed(x) for x in d)}), so these "
                "months do not separate it from LightGBM."
            )
    consistent = [
        lib
        for lib, s in summary.items()
        if lib != "lightgbm" and all(x < 0 for x in s["cost_vs_lightgbm"])
    ]
    if consistent:
        best = min(consistent, key=lambda k: summary[k]["mean_cost"])
        lines.append(
            f"{NAMES[best]} is consistently cheaper. Switching would mean re-freezing it on "
            "April and one new, logged read of May; the frozen LightGBM model is unchanged "
            "until then."
        )
    else:
        lines.append(
            "No library is cheaper than LightGBM in every month, so the evidence supports "
            "keeping it, and its exact, fast SHAP reasons (below) are a further reason."
        )
    return lines


def write_report(result: dict, out_dir: Path) -> Path:
    summary, folds = result["summary"], result["folds"]
    months = [MONTHS.get(f["scored"], f["scored"]) for f in folds]
    s = result["settings"]
    lines = [
        "# Model comparison: LightGBM, XGBoost and CatBoost across three months",
        "",
        "Generated by `fraud compare-models` from the training and validation months only; "
        "**the test month (May) is not read**. The frozen model and policy are unchanged.",
        "",
        "Each fold trains on every month before the one it scores and scores that month "
        f"once. Early stopping and calibration use the last {s['inner_days']} days of the "
        "fold's training window. Each library gets a grid of four settings, the same "
        f"{result['n_features']} features, the same weighting and a "
        f"learning rate of {s['learning_rate']}; its setting is the one with the best mean "
        "PR-AUC over the three months. Money is the cost of the same untuned expected-loss "
        "policy for every model: review whenever the expected saving is positive, within the "
        "daily capacity, so no threshold is tuned on the month being scored.",
        "",
        "## Folds",
        "",
        "| Scored month | Fit rows | Early stopping and calibration | Scored rows | Fraud "
        "| Approve everything |",
        "|---|---|---|---|---|---|",
    ]
    for f, name in zip(folds, months, strict=True):
        lines.append(
            f"| {name} | {f['fit_rows']:,} (to {f['fit_last_day']}) | {f['inner_rows']:,} "
            f"({f['inner_days'][0]} to {f['inner_days'][1]}) | {f['scored_rows']:,} | "
            f"{f['scored_fraud']:,} | {_usd(f['approve_all_cost'])} |"
        )
    lines += [
        "",
        "## Result",
        "",
        "| Library | Setting | PR-AUC "
        + " / ".join(months)
        + " | Mean PR-AUC | Cost "
        + " / ".join(months)
        + " | Mean cost | Cost vs LightGBM | One decision with SHAP |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for lib, r in summary.items():
        vs = "—" if lib == "lightgbm" else " / ".join(_signed(x) for x in r["cost_vs_lightgbm"])
        lat = result.get("latency_ms", {}).get(lib)
        lines.append(
            f"| {NAMES[lib]} | {r['setting']} | "
            + " / ".join(f"{x:.3f}" for x in r["pr_auc"])
            + f" | **{r['mean_pr_auc']:.3f}** | "
            + " / ".join(_usd(x) for x in r["total_cost"])
            + f" | **{_usd(r['mean_cost'])}** | {vs} | "
            + (f"{lat:.1f} ms" if lat is not None else "—")
            + " |"
        )
    lines += ["", *verdict(result), ""]
    base = summary["lightgbm"]["pr_auc"]
    lines += [
        f"Month to month, LightGBM's PR-AUC runs from {min(base):.3f} to {max(base):.3f}; "
        "that spread is the yardstick for any gap between libraries.",
        "",
        "## Every setting",
        "",
        "| Library | Setting | Mean PR-AUC | Mean cost |",
        "|---|---|---|---|",
    ]
    for lib, by_setting in result["all_settings"].items():
        for label, r in by_setting.items():
            mark = " (chosen)" if label == result["best"][lib] else ""
            lines.append(
                f"| {NAMES[lib]} | {label}{mark} | {r['mean_pr_auc']:.4f} "
                f"| {_usd(r['mean_cost'])} |"
            )
    lines += [
        "",
        "Fit time over the three folds for the chosen settings: "
        + ", ".join(f"{NAMES[k]} {v['fit_seconds'] / 60:.1f} min" for k, v in summary.items())
        + ". One decision with SHAP is the median over 200 April rows of scoring one row "
        "with its per-feature contributions.",
        "",
    ]
    path = out_dir / "model_comparison.md"
    path.write_text("\n".join(lines))
    return path
