"""Write ``reports/monitoring.md`` and its figures."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

TITLES = {
    "replay": "Replay of the test month (as streamed)",
    "identity_outage": "Stress scenario: identity feed silent from {outage}",
}


def _plot(results: dict, fig: Path) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    th = results["thresholds"]
    f, axes = plt.subplots(3, 1, figsize=(9, 7.5), sharex=True)
    for name, style in (("replay", "-"), ("identity_outage", "--")):
        d = pd.DataFrame([r for r in results[name]["daily"] if "score_psi" in r])
        x = pd.to_datetime(d["date"])
        label = "replay" if name == "replay" else "identity outage"
        axes[0].plot(x, d["score_psi"], style, label=label)
        axes[1].plot(x, d["drifted_share"], style, label=label)
        axes[2].plot(x, d["alert_rate"], style, label=label)
    axes[0].axhline(th["psi_warn"], color="orange", lw=0.8, ls=":")
    axes[0].axhline(th["psi_alert"], color="red", lw=0.8, ls=":")
    axes[0].set_ylabel("score PSI")
    axes[1].axhline(th["drifted_share_warn"], color="orange", lw=0.8, ls=":")
    axes[1].set_ylabel("share of inputs\ndrifted")
    axes[2].axhline(results["reference"]["alert_rate"], color="grey", lw=0.8, ls=":")
    axes[2].set_ylabel("alert rate")
    axes[0].legend(fontsize=8)
    axes[0].set_title("Trailing 7-day monitors against the validation month", fontsize=10)
    f.autofmt_xdate()
    f.tight_layout()
    f.savefig(fig, dpi=120)
    plt.close(f)


def write_monitoring_report(results: dict, out_dir: Path) -> None:
    fig_dir = out_dir / "figures"
    fig_dir.mkdir(parents=True, exist_ok=True)
    _plot(results, fig_dir / "monitoring.png")
    th, ref = results["thresholds"], results["reference"]
    lines = [
        "# Monitoring",
        "",
        "Generated by `fraud monitor`. Inputs are what production would have seen: the decision",
        "log and raw transactions the stream landed in Delta bronze, and labels as they came off",
        "the labels topic, each 30 days after its transaction. The reference is the validation",
        "month (April 2018) scored with the same model and frozen policy.",
        "",
        "## Thresholds (`configs/monitoring.yaml`)",
        "",
        "| Monitor | Warn | Alert |",
        "|---|---|---|",
        f"| Score drift: PSI of P(fraud), trailing {th['window_days']} days | "
        f"{th['psi_warn']} | {th['psi_alert']} |",
        f"| Input drift: share of monitored inputs drifted (Evidently per-column tests) | "
        f"{th['drifted_share_warn']:.0%} | — |",
        f"| Alert rate (declines + reviews) vs validation's {ref['alert_rate']:.2%} | "
        f"±{th['alert_rate_change_warn']:.0%} relative | — |",
        "| Feed health: a field present on under half its usual share of the latest day's "
        "transactions | — | feed alert (fix the feed; never retrain on it) |",
        f"| Performance of a complete weekly cohort: PR-AUC vs validation's "
        f"{ref['pr_auc']:.3f} | — | below {th['pr_auc_ratio_alert']:.0%} of it |",
        f"| Performance of a complete weekly cohort: fraud value caught vs validation's "
        f"{ref['value_caught']:.1%} | — | {th['value_caught_drop_alert'] * 100:.0f} points "
        "lower |",
        "",
        "**Retrain trigger:** a performance alert on a complete cohort, or a score-drift alert "
        f"on {th['consecutive_score_alert_days']} consecutive days together with an input-drift "
        "warning. A retrain uses every label that has arrived, so it can only ever learn from "
        "transactions at least 30 days old.",
        "",
        "The reference month is also the month the model's early stopping, hyperparameters, "
        "calibration and review threshold were chosen on, so it flatters the model a little: "
        "a cohort has to fall short of a slightly optimistic mark before it alerts.",
        "",
        "![monitors](figures/monitoring.png)",
        "",
    ]
    for name in ("replay", "identity_outage"):
        r = results[name]
        daily = [d for d in r["daily"] if "score_psi" in d]
        title = TITLES[name].format(outage=results["outage_from"])
        worst = max(daily, key=lambda d: d["score_psi"])
        warn_days = sum(d["input_drift_warn"] for d in daily)
        alert_days = sum(d["score_status"] == "alert" for d in daily)
        lines += [f"## {title}", ""]
        if name == "identity_outage" and "before_outage" in results:
            b = results["before_outage"]
            lines += [
                f"Replayed in-process with the same delayed labels. Up to "
                f"{results['outage_from']} it decided all {b['transactions']:,} transactions "
                f"exactly as the stream did (largest P(fraud) difference "
                f"{b['max_p_fraud_difference']:.1e}).",
                "",
            ]
        lines += [
            f"- Score PSI peaked at {worst['score_psi']:.3f} on {worst['date']}; "
            f"{alert_days} of {len(daily)} days at alert level, "
            f"{sum(d['score_status'] == 'warn' for d in daily)} at warn level.",
            f"- Input drift warnings on {warn_days} of {len(daily)} days. Inputs most often "
            "drifted: "
            + (
                ", ".join(
                    f"`{c}` ({n})"
                    for c, n in pd.Series([c for d in daily for c in d["drifted_columns"]])
                    .value_counts()
                    .head(6)
                    .items()
                )
                or "none"
            )
            + ".",
            (
                f"- Feed alert: first on **{r['first_feed_alert']['date']}** ("
                + ", ".join(f"`{c}`" for c in r["first_feed_alert"]["columns"])
                + f"); {sum(bool(d.get('feed_alerts')) for d in daily)} days with a feed alert."
                if r.get("first_feed_alert")
                else "- Feed alerts: none."
            ),
            f"- Retrain trigger: **{r['retrain_on'] or 'not triggered'}**"
            + (f" ({r['retrain_reason']})." if r["retrain_on"] else "."),
            "",
            "| Weekly cohort (transactions from) | Transactions | Labels complete on | PR-AUC "
            "| Fraud value caught | Alert |",
            "|---|---|---|---|---|---|",
        ]
        for c in r["cohorts"]:
            alert = "yes" if (c.get("pr_auc_alert") or c.get("value_caught_alert")) else "no"
            pr = (
                f"{c['pr_auc']:.3f}"
                if c.get("pr_auc") == c.get("pr_auc") and "pr_auc" in c
                else "—"
            )
            vc = f"{c['value_caught']:.1%}" if "value_caught" in c else "—"
            lines.append(
                f"| {c['cohort']} | {c['transactions']:,} | {c['complete_on']} | {pr} "
                f"| {vc} | {alert} |"
            )
        lines.append("")
    lines += [
        "## What the label delay means",
        "",
        "Nothing about a week's fraud can be measured until 30 days after it ends, so the first",
        "complete May cohort is known only in June. The drift monitors are the only signal",
        "available while the month is under way, which is why the retrain rule needs a score",
        "alert that persists and is backed by input drift, not a single noisy day.",
        "",
    ]
    (out_dir / "monitoring.md").write_text("\n".join(lines))
